# -*- mode: org; coding: utf-8; -*-
#+TITLE:              README
#+AUTHOR:         Junahan
#+EMAIL:             junahan@outlook.com
#+DATE:              2018-06-11
#+LANGUAGE:    CN
#+OPTIONS:        H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:        TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT:   view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+LICENSE:         CC BY 4.0

* Abstract
This project is designed for scenes as:
- Use protobuf as internel communication protocol.
- Use protobuf as exchange model to avoid serialize/deserialize persistent model (for example, JPA model) directly.
- Byside the RPC, we want to use protobuf over HTTP and are using Struts2 as web framework.

NOTE: Readme version for [[file:README_cn.org][Chinesee version (中文版本)]] .

* Features
- Populate request protobuf message fields to action object properties automatically.
- Support protobuf message as result - including the succeed response, validation error (field/action error) or exceptions, all of them can be serialized as protobuf message.
- Utils support to populate java model object to protobuf message.

* TODO Quick Start
The plugin-demo project implement a sample echo service as an HelloWorld example. The echo service just response the message what you send. 

** Define Protobuf Message as Interchange Model


** Web Server POM
To use struts2-protobuf-plugin, add following dependency in your POM file.
#+BEGIN_SRC xml
  <dependency>
    <groupId>com.junahan</groupId>
    <artifactId>struts2-protobuf-plugin</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <scope>compile</scope>
  </dependency>
#+END_SRC

** Define Struts2 Action

** Define Struts Configure file

** Run the Example

* TODO FAQ 

* Develper Guide

** Build from Source
- Clone the project from Github
#+BEGIN_SRC sh
git clone https://github.com/junahan/struts2-protobuf-plugin.git
#+END_SRC

- Build and Install
#+BEGIN_SRC sh
cd struts2-protobuf-plugin
mvn install
#+END_SRC

/In this case, it will install a SNAPSHOT version in your local maven repository./

** Run Embbded Jetty with demo-web
The project use maven jetty plugin to run the embbded jetty server for test purpose. 
#+BEGIN_SRC sh
cd plugin-demo/demo-web
mvn jetty:run
#+END_SRC

* Known Issue
- doesn't support to populate protobuf message map type field to Action object property.  In this case, please use a Key/Value message to replace it. For example, 
#+BEGIN_SRC 
message MapEntry {
    optional string key = 1;
    optional string value = 2;
}

message Foo {
    repeated MapEntry map = 1;
}

#+END_SRC

* Todo List
- Support to populate request message map type field to Action object property. 

* References

